baseURL = ""
languageCode = "en-us"
title = "Kube for Hugo"
theme = "kube hugo"
description = "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
Paginate = 4
themesDir = "themes"
publishDir = "public"

[Params]
RSSLink = "/index.xml"
author = "newpixcom"
github = ""
twitter = ""
email = "myemail@myaddress.xxx"

[[menu.main]]
name = "Docs"
weight = -100
url = "/docs/"

[[menu.main]]
name = "Blog"
weight = -100
url = "/blog/"

[[menu.main]]
name = "Faq"
weight = -100
url = "/faq/"
